module.exports = {
  docs: [
    'index',
    'persona',
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items:[
        'quickstart',
        'tut-deployment',
        {type:'doc', id:'uninstall'},
      ],
    },
    {
      type: 'category',
      label: 'Explanations',
      collapsed: false,
      items:[
        'concepts',
        'glossary',
        'architecture',
        'ref-bundle-stages',
        'gitrepo-content',
        'namespaces',
        'resources-during-deployment',
      ],
    },
    {
      type: 'category',
      label: 'How-tos for Operators',
      collapsed: false,
      items:[
        {type: 'doc', id: 'installation'},
        {type: 'doc', id: 'cluster-registration'},
        {type:'doc', id:'cluster-group'},
        'multi-user',
      ],
    },
    {
      type: 'category',
      label: 'How-tos for Users',
      collapsed: false,
      items:[
        {type:'doc', id:'gitrepo-add'},
        {type:'doc', id:'gitrepo-targets'},
        {type:'doc', id:'bundle-diffs'},
        {type:'doc', id:'oci-storage'},
        {type:'doc', id:'fetch-helm-oci'},
        {type:'doc', id:'webhook'},
        {type:'doc', id:'imagescan'},
        {type:'doc', id:'bundle-add'},
        {type:'doc', id:'observability'},
        {type:'doc', id:'helm-ops'},
        {type:'doc', id:'rollout'},
        {type:'doc', id:'fine-tune-error'}
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items:[
        {
          'CLI': [
            'cli/fleet-agent/fleet-agent',
            'cli/fleet-agent/fleet-agent_clusterstatus',
            'cli/fleet-agent/fleet-agent_register',
            {type: 'doc', id: 'cli/fleet-cli/fleet'},
            {type: 'doc', id: 'cli/fleet-cli/fleet_apply'},
            {type: 'doc', id: 'cli/fleet-cli/cleanup/fleet_cleanup'},
            {type: 'doc', id: 'cli/fleet-cli/cleanup/fleet_cleanup_clusterregistration'},
            {type: 'doc', id: 'cli/fleet-cli/cleanup/fleet_cleanup_gitjob'},
            {type: 'doc', id: 'cli/fleet-cli/fleet_deploy'},
            {type: 'doc', id: 'cli/fleet-cli/fleet_target'},
            {type: 'doc', id: 'cli/fleet-cli/fleet_test'},
            {type: 'doc', id: 'cli/fleet-controller/fleet-controller'},
            {type: 'doc', id: 'cli/fleet-controller/fleet-controller_agentmanagement'},
            {type: 'doc', id: 'cli/fleet-controller/fleet-controller_cleanup'},
            {type: 'doc', id: 'cli/fleet-controller/fleet-controller_gitjob'},
          ],
        },
        {type:'doc', id:'ref-status-fields'},
        'ref-registration',
        'ref-configuration',
        'ref-resources',
        "ref-crds",
        'ref-fleet-yaml',
        'ref-gitrepo',
        'ref-bundle',
      ],
    },
    'troubleshooting',
    {
      "type": "category",
      "label": "Changelog",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "changelogs/changelogs"
        }
      ]
    },
    {
      type: 'category',
      label: 'Experimental Features',
      collapsed: false,
      items:[
        'enableexperimental',
        'scheduling'
      ],
    },
  ],
};
